# Generated by Django 5.2.14 on 2026-05-25 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('selector', models.TextField(verbose_name='Seletor')),
                ('selector_type', models.CharField(choices=[('css', 'CSS'), ('xpath', 'XPath')], default='css', max_length=10, verbose_name='Tipo')),
                ('expected_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('url', 'URL'), ('any', 'Qualquer')], default='any', max_length=10, verbose_name='Tipo de dado esperado')),
                ('min_results', models.PositiveIntegerField(default=1, verbose_name='Mínimo de resultados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Seletor',
                'verbose_name_plural': 'Seletores',
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('url', models.URLField(unique=True, verbose_name='URL alvo')),
                ('check_interval_minutes', models.PositiveIntegerField(default=60, verbose_name='Intervalo de verificação (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Detectado em')),
                ('change_type', models.CharField(blank=True, max_length=60, verbose_name='Tipo de mudança')),
                ('old_html_fragment', models.TextField(blank=True, verbose_name='HTML anterior')),
                ('new_html_fragment', models.TextField(blank=True, verbose_name='HTML atual')),
                ('diff_report', models.TextField(blank=True, verbose_name='Diff')),
                ('suggested_selectors', models.JSONField(blank=True, null=True, verbose_name='Sugestões do LLM')),
                ('validation_results', models.JSONField(blank=True, null=True, verbose_name='Resultados de validação')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('selector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='monitor.selector')),
            ],
            options={
                'verbose_name': 'Evento de falha',
                'verbose_name_plural': 'Eventos de falha',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddField(
            model_name='selector',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectors', to='monitor.site'),
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_fragment', models.TextField(blank=True, verbose_name='Fragmento HTML')),
                ('extracted_value', models.TextField(blank=True, verbose_name='Valor extraído')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Falhou')], max_length=10, verbose_name='Status')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Verificado em')),
                ('selector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitor.selector')),
            ],
            options={
                'verbose_name': 'Snapshot',
                'verbose_name_plural': 'Snapshots',
                'ordering': ['-checked_at'],
            },
        ),
    ]
