# Generated by Django 5.2.14 on 2026-07-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        # Campos novos: criados de fato no banco.
        migrations.AddField(
            model_name='changeevent',
            name='applied_selector',
            field=models.TextField(blank=True, verbose_name='Seletor aplicado'),
        ),
        migrations.AddField(
            model_name='changeevent',
            name='auto_healed',
            field=models.BooleanField(default=False, verbose_name='Curado automaticamente'),
        ),
        # Colunas que já existem no banco mas não estavam registradas em migração:
        # sincroniza apenas o estado do Django, sem executar DDL (evita "duplicate column").
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='selector',
                    name='anomaly_threshold',
                    field=models.PositiveIntegerField(blank=True, help_text='Gera alerta se o valor numérico variar mais que X% em relação à última leitura. Deixe vazio para desativar.', null=True, verbose_name='Alerta de variação (%)'),
                ),
                migrations.AddField(
                    model_name='snapshot',
                    name='failure_reason',
                    field=models.CharField(blank=True, choices=[('selector_empty', 'Seletor sem resultados'), ('http_error', 'Erro HTTP (4xx/5xx)'), ('network_error', 'Erro de rede/conexão'), ('type_mismatch', 'Tipo de dado incorreto')], max_length=20, verbose_name='Motivo da falha'),
                ),
            ],
            database_operations=[],
        ),
    ]
